### ISSUE TITLE
Any option to change the headers in sign method ?

### ISSUE THREAD

**Issue by HiroshiHorie** [jonasroussel/dart_jsonwebtoken#12]
It looks like it's hard-coded now, but it would be nice if I could provide this in parameters.
For example, Sign in with Apple requires "kid" in the header.

For my own purpose, I will create a fork.

Thank you!
Hiroshi

**Comment by jonasroussel** [comment]
Hello,

It's a good idea. I will add this option soon. probably something like this :

```dart
JWT(
  { 'foo': 'bar' },
  customHeaders: { 'kid': '...' }
);
```

**Comment by jonasroussel** [comment]
Added in v2.3.0 (https://pub.dev/packages/dart_jsonwebtoken/versions/2.3.0)
