### ISSUE TITLE
issue on checking audience 

### ISSUE THREAD

**Issue by walid1001** [jonasroussel/dart_jsonwebtoken#18]
hi 
with this condition the code never check the audience
 
https://github.com/jonasroussel/dart_jsonwebtoken/blob/855be021a6b7f46f711aeee181ab2744251dfc25/lib/src/jwt.dart#L97

when aud is set the code need to fire an exception even if the token don't contains that aud 

regards

**Comment by jonasroussel** [comment]
Merged ! https://github.com/jonasroussel/dart_jsonwebtoken/pull/19

Will be in the next version : v2.4.1
