### ISSUE TITLE
Where the function to read the payload after encode?

### ISSUE THREAD

**Issue by SittiphanSittisak** [jonasroussel/dart_jsonwebtoken#28]
After encoding in the dart server, the token was sent to the flutter app. Where is the function to read payload from this token in the flutter app?
(Or I must create [custom function](https://stackoverflow.com/a/52021206/17798537) or use a [package](https://pub.dev/packages/jwt_decoder) ?)

**Comment by yuriboeira11tx** [comment]
I used this way to use token coming from server
`try {
    final jwt = JWT.verify(
      response.data,
      SecretKey("YOUR_SECRET_KEY"),
    );

    log('Payload: ${jwt.payload}');

    return jwt.payload; <--
  } on JWTExpiredError {
    log('jwt expired');
  } on JWTError catch (ex) {
    log(ex.message);
  }`

**Comment by jonasroussel** [comment]
Hello @SittiphanSittisak,

I just added a new function `JWT.decode` in this new version (https://pub.dev/packages/dart_jsonwebtoken/versions/2.6.0)

Hopefully this will meet your needs

**Comment by SittiphanSittisak** [comment]
Hi @jonasroussel, thank you so much!
This makes code beautiful and there is no need to use more packages.
```
(
          ? JWT.decode(jwt)
          : JWT.verify(jwt, SecretKey(secretKey));
).payload
```
