### ISSUE TITLE
Bug: verify() always throws JWTUndefinedError instead of JWTError

### ISSUE THREAD

**Issue by ynnob** [jonasroussel/dart_jsonwebtoken#32]
Because JWTError extends Error the folowing condition is always true and throws a JWTUndefinedError:

```
catch (ex) {
     if (ex is Error) {
        throw JWTUndefinedError(ex);
      } else {
        rethrow;
      }
    }
```

To throw a JWTError we need to first check for `ex is JWTError` and rethrow there before we check other cases.

**Comment by jonasroussel** [comment]
Published! https://pub.dev/packages/dart_jsonwebtoken/versions/2.6.2
