### ISSUE TITLE
Feature Request: Direct use of pointy castle keys

### ISSUE THREAD

**Issue by nblum37** [jonasroussel/dart_jsonwebtoken#35]
Hi :)

currently, the framework allows importing PEM keys. As the framework also uses pointy castle keys internally, it would be nice, if it would be possible to directly use pointy castle keys instead of converting them to a PEM string first and then parsing them back to the framework key class. Thank you!

**Comment by jonasroussel** [comment]
Hello !

I totally understand the need. So I pushed a new version (v2.6.3) that includes this feature on all `JWTKey`
https://pub.dev/packages/dart_jsonwebtoken/versions/2.6.3

You can now instantiate a `JWTKey` like this:

```dart
final pcKey = pc.RSAPrivateKey(modulus, privateExponent, prime1, prime2);

...

final key = RSAPrivateKey.raw(pcKey);
```

**Comment by nblum37** [comment]
Nice! Thank you :)

**Comment by nblum37** [comment]
I run into the attached issue with ECDSA keys. It seems like, the new `.raw` method does not initialize the `size` property.
<img width="552" alt="Bildschirm­foto 2023-01-24 um 00 20 52" src="https://user-images.githubusercontent.com/82163574/214174608-ba2f1c87-ffa1-425f-84a8-881dd2ca3733.png">

**Comment by jonasroussel** [comment]
Yeah right ! Fixed : https://pub.dev/packages/dart_jsonwebtoken/versions/2.6.4

**Comment by nblum37** [comment]
Nice, seems to work now :)
