### ISSUE TITLE
IAT Custom

### ISSUE THREAD

**Issue by yuriboeira11tx** [jonasroussel/dart_jsonwebtoken#37]
Hello I wonder if there is any way to put the "iat" (issued at) key manually with this package? Apparently my server is delayed by a matter of milliseconds from the "iat" generated by the package. Any suggestions?

**Comment by jonasroussel** [comment]
Yes you can, `iat` is added during the sign method. You can simply add a custom `iat` inside your JWT payload and set to `true` the `noIssueAt` param of the sign method.

```dart
final jwt = JWT({ 'iat': 1674388 });
final token = jwt.sign(SecretKey('secret passphrase'), noIssueAt: true);
```
