### ISSUE TITLE
When will the ES256K be added?

### ISSUE THREAD

**Issue by chobyungkwon** [jonasroussel/dart_jsonwebtoken#43]
Are there any plans to add the ES256K? 
If yes, when are you planning? 
I like the function so much that I really want to use it when the ES256K is added

**Comment by jonasroussel** [comment]
Hey! Thank you for your interest!

I do plan on adding the missing algorithms in my upcoming version (v2.9.x),
- PS256
- PS384
- PS512
- And ES256K

However, I currently have a lot of works in my job (got promoted CTO), so I cannot provide a precise date for that release. But, I will try my best to publishing it before the end of June.

**Comment by jonasroussel** [comment]
Hey! I just published a new version v2.10.0 that include all the new algorithms and of course the ES256K that you requested!
https://pub.dev/packages/dart_jsonwebtoken/versions/2.10.0
