### ISSUE TITLE
Dependencies conflicts with flutter_test at latest version 2.8.1

### ISSUE THREAD

**Issue by 89pleasure** [jonasroussel/dart_jsonwebtoken#44]
Hey there! Thanks for that awesome library. 
I'm using it together with flutter and having a dependency conflict with core lib flutter_test. 
I need to use 2.8.0 to get it work. Could u look into it?

`Because every version of flutter_test from sdk depends on collection 1.17.1 and dart_jsonwebtoken >=2.8.1 depends on collection ^1.17.2, flutter_test from sdk is incompatible with dart_jsonwebtoken >=2.8.1.`

**Comment by jonasroussel** [comment]
Hi, thanks for your support!

I will take a look, but doesn't seem to be a problem to downgrade the minor version of this library.

**Comment by jonasroussel** [comment]
Done ✅ (https://pub.dev/packages/dart_jsonwebtoken/versions/2.8.2)

**Comment by 89pleasure** [comment]
Thank you! :)
