### ISSUE TITLE
Verify Firebase token failure

### ISSUE THREAD

**Issue by fabiotavares** [jonasroussel/dart_jsonwebtoken#45]
I can't verify the signature of a valid token generated by Firebase. 
Using JWT.verify(token, RSAPublicKey(key)) gives the following conversion error:

type 'ASN1Integer' is not a subtype of type 'ASN1ObjectIdentifier' in type cast RSAPublicKey

I'm using a jwt.io validated token and the public key:
'-----BEGIN CERTIFICATE-----\nMIIDHTTCCAgWgAwIBAgIJAN6IA4cSjd2+MA0GCSqGSIb3DQEBBQUAMDExLzAtBgNV\nBAMMJnNlY3VyZXRva2VuLnN5c3RlbS5nc2VydmljZWFjY291bnQuY29tMB4 XDTIz\nMDgwMjA5Mzk0MFoXDTIzMDgxODIxNTQ0MFowMTEvMC0GA1UEAwwmc2VjdXJldG9r\nZW4uc3lzdGVtLmdzZXJ2aWNlYWNjb3VudC5jb20wggEiMA0GCSqGSIb3DQEBAQUA\nA4IBDwA wggEKAoIBAQC09EdXFC4DxPlpxqJWl/0jwnenb7Ghp+zUDnkoV6Z9bt3w\n+fJWhz4aw2yGRdxc/ZWr7W3/8XA5rDPhMognuEHE8Pfoysn4T4mRzhB99y2DiIC7\nmmvuF+ty7jq6o0ToAZ8vV2 o6h3IYetNmtPO6vm8PFXBFnL8YgnhmFtPRGZeIuwty\ny+uaJsux/SjCf1OTQZRvRW+X0EiNspU4GpakCgUGLuIXfrrludzcCzUO65KtIbls\ nbsNqri7XbFgRTv1drnoHIB7qOztL/FuwjK00QZfxGfBgYVi83J18kVRp+Si0EN0i\nf6rzm3tYKpJuGf+aWTCRcIgNRfRtrl7pwg4IX7yxAgMBAAGjODA2MAwGA1UdEwEB\n/wQCMAAwDg YDVR0PAQH/BAQDAgeAMBYGA1UdJQEB/wQMMAoGCCsGAQUFBwMCMA0G\nCSqGSIb3DQEBBQUAA4IBAQCb+IU6a+AVza7UfloHGwAvfYRCoOF80kYrkEH24zUF\ndxGrCqIJFrxhN5MXv0GiZ1Ij/TZcf RCZo+noFJzB/1sB2JEaSIijaLoohVWUR699\nW4yND6dpIUWlevaYKbrZJlX7+zid+eLNzcBMF9yd+y/vJdnCe0+jGiFDljHnDt32\nx9Y3GvMmKvu/Om/deK3oHegktWHK3udb8PX4u9x tQA5+ vuMWnIZ92HsinuglqMuX\ng8CoiXkjdRVkAukCPimp0iJkdaCCSk5Vd91uy8y1kDN81p0nxQj2E/7IA6Qz6yrU\nh8nuwArb0VS0DWcUVYaw2ZoSlVnHvFkAmZRV4MsqCoVg\n-----END CERTI STAY-----\n'

**Comment by Bkohler93** [comment]
Similar issue but occurring with a Google public key.

`type 'ASN1Sequence' is not a subtype of type 'ASN1Integer' in type cast`

Were you able to figure it out?

**Comment by jonasroussel** [comment]
Hey!

The package does not currently support PEM certificate parsing because only the public key is needed to validate the token.

I'll see if I can add a certificate parser in middleware to extract the public key before starting the validation.

**Comment by jonasroussel** [comment]
Let me know if this new function works for you in the case of the Firebase certificate

**Comment by fabiotavares** [comment]
> Let me know if this new function works for you in the case of the Firebase certificate

Hi,
Worked perfectly!
Thank you very much for your attention and commitment.
Congratulations.
