### ISSUE TITLE
Validate Auth0 JWT Fail - RangeError: Value not in range

### ISSUE THREAD

**Issue by Lasse-Fisker** [jonasroussel/dart_jsonwebtoken#46]
HI there! 

I'm trying to validate a jwt token from auth0 in my flutter app obtained using the auth0 authentication api. I can validate the jwt on jwt.io using the client secret from the Auth0 dashboard.

At first I tried just using `SecretKey(key)`, but got an error that the key needed to be an RSAPublic one. After changing this I got an error regarding my key not having the correct start / end markers for a pem file. I fixed this by adding them manually

```
JWT.tryVerify(credentials.idToken, RSAPublicKey("""
 -----BEGIN PRIVATE KEY-----
  (My secret key goes here)
  -----END PRIVATE KEY-----
"""));
```

Now however, I get the error in the title: RangeError: Value not in range: -9167323145251028292. The key is not base64 encoded if that makes a difference. Since I can validate the jwt on jwt.io, I am certain that it is a question of me doing something wrong in my configuration, but I cannot see what? Does anyone here spot any mistakes?

Thanks in advance

**Comment by jonasroussel** [comment]
Hey!

If your key doesn't have a start / end markers, it means that your key is probably in a binary format and not encoded to support the PEM PKCS format.

Can you give me a string example that look like your key, if the format is standard it should be parseable

**Comment by jonasroussel** [comment]
Closed for inactivity!
