### ISSUE TITLE
Non repeatable result with fixed parameters

### ISSUE THREAD

**Issue by davidsowerby** [jonasroussel/dart_jsonwebtoken#52]
I set this up as a simple code generator, but found that with fixed parameters it gives a different result at each run:

```dart
import 'package:dart_jsonwebtoken/dart_jsonwebtoken.dart';

void main() {
  final expiry = DateTime(2025, 2, 4).millisecondsSinceEpoch ~/ 1000;
  final jwt = JWT(
    {
      'exp': expiry,
      'name': 'token test',
    },
  );

  final key = 'xxxyyyxxxyyyxxxyyyxxxyyyxxxyyyxxx';

  if (key.length < 32) {
    throw Exception(
        'Key must be at least 32 characters long for pgrest see https://postgrest.org/en/stable/references/configuration.html#jwt-secret');
  }

  final token = jwt.sign(SecretKey(key));
  print(token);
}
```

I don't think this is expected behaviour?  It differs from jwt.io where I can enter the same parameters and get the same result every time

**Comment by jonasroussel** [comment]
Hello,

This is because at the signature of the JWT an `iat` (issuedAt) value is added, that is the timestamp when the token has been signed.

I changed a bit your code to have predictible output:
```dart
```

**Comment by davidsowerby** [comment]
Ah, thanks, that solves it
