### ISSUE TITLE
Privacy manifest file for iOS is missing

### ISSUE THREAD

**Issue by oremlawi** [jonasroussel/dart_jsonwebtoken#53]
Kindly consider adding a privacy manifest to your library following the new apple policy by adding `PrivacyInfo.xcprivacy` file to your project.

For more information, please check [Apple's documentation](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files).

**Comment by jonasroussel** [comment]
Thanks for your request, but I don't think I should include such files in this library, as written in the first line “Apps and third-party SDKs - **_distributed as XCFrameworks, Swift packages, or Xcode projects_**”. This lib is not an XCode SDK, it's only Dart code. You may therefore need to add this file to your own XCode project folder.
